server:
  port: 9000

spring:
  application:
    name: APIGATEWAY


  cloud:
    gateway:
      routes:
        - id: PRODUCT-SERVICE
          uri: lb://product-Service
          predicates:
            - Path=/api/product/**

  eureka:
    client:
      service-url:
        defaultzone: http://localhost:8761/eureka

keycloak:
  realm: microservicenew
  auth-server-url: http://localhost:8080/
  resource:  keycloak-client
  public-client: true
  bearer-only: true

